onboarding:
  modules:
    - name: ida
      enabled: true
    - name: print
      enabled: true
    - name: abis
      enabled: true
    - name: resident
      enabled: true
    - name: mobileid
      enabled: true
    - name: digitalcard
      enabled: false
    - name: esignet
      enabled: false
    - name: mock-rp-oidc
      enabled: false
    - name: resident-oidc
      enabled: false
    - name: mimoto-keybinding
      enabled: false
    - name: mimoto-oidc
      enabled: false
    - name: signup-oidc
      enabled: false
  variables:
    push_reports_to_s3: true
    mosipid: false
