{{- range $module := $.Values.onboarding.modules }}
{{- if $module.enabled }}
{{- if eq $.Values.onboarding.variables.push_reports_to_s3 false }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.onboarding.volumes.reports.name }}-{{ $.Release.Namespace }}-{{ $module.name }}-pvc
  labels:
    name: {{ $.Values.onboarding.volumes.reports.name }}
spec:
  storageClassName: {{ $.Values.onboarding.volumes.reports.storageClass }}
  capacity:
    storage: {{ $.Values.onboarding.volumes.reports.size }}
  accessModes:
    {{- range $.Values.onboarding.volumes.reports.accessModes }}
      - {{ . }}
    {{- end }}
  nfs:
    server: {{ $.Values.onboarding.volumes.reports.nfs.server }}
    path: {{ $.Values.onboarding.volumes.reports.nfs.path }}
#  mountOptions:
#    - nolock
{{- end }}
{{- end }}
{{- end }}
