{{- range $module := $.Values.onboarding.modules }}
  {{- if and $module.enabled (eq $.Values.onboarding.variables.push_reports_to_s3 false) }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.onboarding.volumes.reports.name }}-{{ $.Release.Namespace }}-{{ $module.name }}-pv
  labels:
    name: {{ $.Values.onboarding.volumes.reports.name }}

spec:
  capacity:
    storage: {{ $.Values.onboarding.volumes.reports.size }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $.Values.onboarding.volumes.reports.storageClass }}

  accessModes:
    {{- range $.Values.onboarding.volumes.reports.accessModes }}
    - {{ . }}
    {{- end }}

  {{- if eq $.Values.onboarding.volumes.reports.storageClass "nfs-csi" }}
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: {{ $.Values.onboarding.volumes.reports.name }}-{{ $.Release.Namespace }}-{{ $module.name }}-volume-id
    volumeAttributes:
      server: {{ $.Values.onboarding.volumes.reports.nfs.server }}
      share: {{ $.Values.onboarding.volumes.reports.nfs.path }}
  {{- else }}
  nfs:
    server: {{ $.Values.onboarding.volumes.reports.nfs.server }}
    path: {{ $.Values.onboarding.volumes.reports.nfs.path }}
  {{- end }}

  {{- end }}
  {{- end }}
